### ISSUE TITLE
Please add documentation for webr-teachr thanks 

### ISSUE THREAD

**Issue by DanyangDai** [learnr-academy/quarto-forms-teachr#1]

**Comment by DanyangDai** [comment]
Adding documentation for checking if students put in the correct arguments for functions. 

- This is to check to see if any of the arguments in the function contains "cars"
`c("responese you want to put in" != "cars" %in% all.vars(.code))`

- To check for the location for the arguments i.e. the function contains multiple arguments, you might want to use [] to locate the functions. 
 `str(<<cars>>)`
 `???`
 `p <- .code[[1]][[2]][[2]]`

**Comment by DanyangDai** [comment]
Would love to have the `?` help function work in webr but not urgent. Thanks

**Comment by mitchelloharawild** [comment]
Migrated these questions to the more appropriate home of https://github.com/learnr-academy/quarto-webr-teachr - I hadn't realised that the issues were disabled for that repo since it was a fork.
